sudo: required
dist: trusty
group: edge

services:
  - docker
language: python
python:
  # - 2.7
  - 3.6
branches:
  only:
    - master

env:
  - INTERFACE_TO_BUILD=none
  - INTERFACE_TO_BUILD=ants
  - INTERFACE_TO_BUILD=fsl
  - INTERFACE_TO_BUILD=miniconda
  - INTERFACE_TO_BUILD=mrtrix3
  - INTERFACE_TO_BUILD=spm
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install pytest-cov
script:
  - function run_tests {
      if [ "$INTERFACE_TO_BUILD" == 'none' ]; then
        python -m pytest -v -k "not test_build_image" --cov=./ neurodocker;
      else
        travis_wait 50 python -m pytest -v -k "test_build_image_$INTERFACE_TO_BUILD" --cov=./ neurodocker;
      fi }
  - run_tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
