sudo: required
dist: trusty
group: edge
services:
  - docker
language: python
python:
  - 3.6
branches:
  only:
  - master
env:
  matrix:
  - INTERFACE_TO_BUILD=none
  - INTERFACE_TO_BUILD=afni
  - INTERFACE_TO_BUILD=ants
  - INTERFACE_TO_BUILD=convert3d
  - INTERFACE_TO_BUILD=freesurfer
  - INTERFACE_TO_BUILD=fsl
  - INTERFACE_TO_BUILD=miniconda
  - INTERFACE_TO_BUILD=mrtrix3
  - INTERFACE_TO_BUILD=neurodebian
  - INTERFACE_TO_BUILD=spm
  global:
  - secure: YQAc7V0h4jIVJJmY47no4OyQolMv49wqM4xbtkRB3SZE6GonoplcB0iP8olvWn0XJF9dDVXQzU+NhVTDk8sSY+tiuU0pClPMkGC1KfxD6uNDVW26nQIa6FcDy17xayOH3UxB2DSl6ZlqHwXx1Lb0hgoDluGVnz2i8mJWpZycNr/C94RIIKCEQHPV8hu30VtHJcowzv8/LoZ1wgWQeAg08azXcx9h4yfOcvSoH9fvliD3C71fvLiwDugbJ5+6dgF1Pqyq6wjwsopE9PxAanariqoMITpqHAFgaqMeyXirr/a1y4Xgnf5PB/Ci86VZgZ6KrMRez9UlpePHKA06WW5wdUeMPTFL4B38EEtV5l6RwswZHrypoL3t0WS+uLtwqYoyMzAmKf63dBZPhwzv0xHrziriOB0MNfgsUHulzayxgcHiQr0G8hPG09OIvNPNwuy4ije+GUENL8wMUZHuQ22Nw9YyPTbGWsxYRfG2GTcR7qmb+TpfPJlbVMiVg2bqN+6vbREyeU0rXSEFTNqF3WOYEUzoen8QDj4Jh8D63Ew1vc0awjxvF98O3puUjYdrooJr1nyufQdPXqAsvszHm8NnUpBGgG4eEox+VIAw1De5HhMmsRqn7LNzgTueRLRtIIN+DeaI8xV4qZMrvkdyvqgJR8elWKay/21WS69o8Wmb8KA=
  - secure: NbPJOFqRvWeWps5kc/QUYN8n57w0cHut9N51uX1Y+/sU0Z5SBY/0SHTPZu2sypSNzB73RVCBonJ1nyBFtI0qzQUmPIjxa5MpGLkltsDom3x0jGGaY2/1mgWSck59PFajK7l89W1M0kB9OEEzwiq0Htrq3cLu2IKyXenLtYkhvT9A2INAh4dxuQ32tj8ksRlmH+TNd/7bj22Et+Wz/k/tTRNuttR6mrmQl74nydQhRjOzn/OgSOp6EPn+FqXkfPMMNrgLxKmGWi/+uIzllWc3uvUSMXxwcATf755odNpcuIJoXBYLiaYka4xpe/L+Yuw1PFAHFRuPVCgewFY6tejizF6++mKR31k1KTmhGyYgQB1M7J3X+karu/qgvv26K+VGX3egoLlKFCMBKqYp33fTc2F6HUKoSPO2JnvPR8yCEL6u5bmRuIY4UiDuk6xxENMLMyuoXuTDOueb67jUtwGi7gwu9Bjtk5Vi2TOKNs7I9aXQyvUyeP48VYiQuJ9jmKW4J32DwDV0FvIohv5oPK2X6w1hTDMsP57Rka8R7/DS7eiO8vqwekwzTdFGOSK1qzKkr6Dt5cVYqQpskuUKH+28Z5DJ1Q5UYuXM6UfRizMzgq4n2GwyjSVYMgxEXJwQhzx0OsUQbm3YRZ9eUxJqqMQ+G5oMD8hFpkdMxmu5JjxOW/o=
  - secure: PdajcfJAm+ePQFOKcLRZDwlT0pKiTEABXs3u0R/lFfxR7Vl0TZ/R7TSfEDzDdPOODvjInqbCaIBcGXgu+JxrkkoREdmS3b997yq1HjQxFsnmWty/qJ5AHAPkIfBFHS0/cr6RU4Sgiq1jibAMvW9MnGFybyiwOGeo79bXwx55rLzJ8+XGWL1xeAfK3nvajSjK91STugeREwXlyg5CYTR+RJnCVIqQySBZNkn+LhPX0vkpMJ3Ab0ONcuhSwlv6enP0CLuc/4xaC+/6bKQ84W1iw5eTvltv4VcUnVsN1FRG+VAudlg4/qDZ6q7d9pPNxQ5HajhTdE8Gds4x2pxqQTjFCH475eMQVoSbDjjGsuixqxntY2Wx/L4UWMUAST1GsNefofyTvIYKWcN5PjQaD+bR3sRDcYe1tb8Ew01T4zu4eGJ9VhrUIrerS4L2Qatn8EDgmN6kzDzWXdDzwkuumjaC/7OaNtQ6sJ4lBgae5hbcMQlwCk1o/IuKnjzt1K8YvqDLa5DZGyJfJk+GXKOyFp1pTWD0d/blgAw3JlkFLebmL3r3heKVmDHIqhT1FeqY5jIuy0rhsOXEopwCrLHCC/0Mo0baJKmAL1a8zdQTvn9oZMfYZtK1C4RWqV6nOSjxi/RXRfz/XJcTes3v/o4mrrjkjui6kfxSF0jkth4HFGWhBhc=
before_install:
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -yq libsqlite3-dev
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install dropbox pytest-cov reprozip
script:
  - function run_tests {
    if [ "$INTERFACE_TO_BUILD" == 'none' ]; then
    python -m pytest -v -k "not test_build_image" --cov=./ neurodocker;
    else
    travis_wait 50 python -m pytest -v -k "test_build_image_$INTERFACE_TO_BUILD" --cov=./ neurodocker;
    fi }
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - run_tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
