---
name: Auto-release on PR merge

on:
  # ATM, this is the closest trigger to a PR merging
    push:
        branches:
        -   master

env:
    AUTO_VERSION: v11.3.0

jobs:
    auto-release:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
        steps:
        -   uses: actions/checkout@v6

        -   name: Prepare repository
        # Fetch full git history and tags
            run: git fetch --unshallow --tags

        -   name: Unset header
        # checkout@v2 adds a header that makes branch protection report errors
        # because the Github action bot is not a collaborator on the repo
            run: |
                if git config --local --get-all http.https://github.com/.extraheader > /dev/null; then
                    git config --local --unset-all http.https://github.com/.extraheader
                fi

        -   name: Set up Python
            uses: actions/setup-python@v6
            with:
                python-version: '3.11'

        -   name: Download auto
            run: |
                auto_download_url="$(curl -fsSL https://api.github.com/repos/intuit/auto/releases/tags/$AUTO_VERSION | jq -r '.assets[] | select(.name == "auto-linux.gz") | .browser_download_url')"
                wget -O- "$auto_download_url" | gunzip > ~/auto
                chmod a+x ~/auto

        -   name: Create release
            run: |
                ~/auto shipit -vv
            env:
                GH_TOKEN: ${{ secrets.AUTO_USER_TOKEN }}

        -   name: Build Docker images
            if: steps.auto-version.outputs.version != ''
            run: |
                docker build \
                  -t repronim/neurodocker:master \
                  -t repronim/neurodocker:latest \
                  -t repronim/neurodocker:"$(git describe | sed -e 's,^v,,g')" \
                  .

        -   name: Push Docker images
            if: steps.auto-version.outputs.version != ''
            run: |
                docker login -u "$DOCKER_LOGIN" --password-stdin <<<"$DOCKER_TOKEN"
                docker push --all-tags repronim/neurodocker
            env:
                DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
                DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
